### ISSUE TITLE
LevelProperty.

### ISSUE THREAD

**Issue by Beejeedeb** [tim-hellhake/counter-adapter#2]
Hello Tim,

Again another very good add-on, simple but effective. (thumbs up)

Is it possible to give a property to a thing. Now one can only choose a custom thing with your counter add-on.

![Custom Thing](https://user-images.githubusercontent.com/51539492/63653640-ce6c1d80-c76f-11e9-90f7-760df1b296e0.png)

You could use (misuse) the (multi)LevelProperty just like @mrstegeman does with his Speed test add-on.

Counter:
For the counter add-on you could set the minimum default to 0 and maximum default to 100000000, whereby one can adjust the maximum value in configure. Unit is units or counts ??

You could also use levelProperties with your other add-ons.
OpenUV - Clear sky UV index:
UV level, minimum zero and maximum 10 or Ozon level with a minimum of 100 and maximum of 500, unit is Dobson Unit (DU).

MI Flora:
I ordered two. Do not know what is being shown now.

Timer:
Same as Counter but the other way around. Where you can set maximum in configure. Level property is getting lower. Unit is seconds (s)

**Comment by tim-hellhake** [comment]
Sorry I wasn't aware of this issue.
That's definitely a good idea.
I already did that for all properties of the mi flora device where I have a defined maximum value.

**Comment by kgiori** [comment]
Thanks for this useful add-on. I wish I could be a PR submitter for little requests like this. I am using the Counter add-on for some [MicroBlocks](microblocks.fun) web thing testing and I find it super helpful to track when my test sensor or actuator thing dies. I'd like to be able to see the count from the main things page icon rather than opening it via the splat bubble. 

In other words, each configured Counter should by default be defined as having a default capability of [MultiLevel Sensor](https://iot.mozilla.org/schemas/#MultiLevelSensor).

**Comment by tim-hellhake** [comment]
I thought I already covered the counter adapter.
Thanks for the hint!
